Feature/chatting
wooyeon0626/wooyeon pull request #13
Opened 2023-07-15 06:29 UTC by tenta3802

2023-07-15 13:29 UTC, hesoo98 requested changes
@OneToOne(fetch = FetchType.LAZY)로 설정 부탁합니다.

2023-07-15 13:29 UTC, hesoo98 commented on src/main/java/com/wooyeon/yeon/chat/domain/Chat.java
> +    @OneToOne
@OneToOne(fetch = FetchType.LAZY)로 설정 부탁합니다.

2023-07-15 13:49 UTC, Haneol approved these changes

2023-07-17 14:12 UTC, easyoungcode approved these changes

2023-07-30 09:55 UTC, merged